### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by AlvL1225** [HuangLK/llama-deepspeed#28]
Hi Huang, nice work!

when I tried to train with a 13B model, I got the error:
[Errno 2] No such file or directory: 'llama_13b_pp/global_step001/zero_pp_rank_0_mp_rank_03_optim_states.pt'

Any ideas on this? The 'convert2ckpt.py' script does not generate files with prefix 'zero_pp_....'

**Comment by HuangLK** [comment]
add `load_optimizer_states=False` and `load_lr_scheduler_states=False` while [loading checkpoint](https://github.com/HuangLK/llama-deepspeed/blob/faedea514b11c18c695e1b2a6adb63b102ef001c/train.py#L108).
```python
    engine.load_checkpoint(model_args.init_ckpt,
                           load_module_only=True,
                           load_optimizer_states=False,
                           load_lr_scheduler_states=False,
    
```

**Comment by HuangLK** [comment]
In addition, I modified the way deepspeed is loaded, so that it can skip zero_pp_xxx when initializing.
