### ISSUE TITLE
How to set distributed sampler when using hybrid training of pipeline parallelism and data parallel

### ISSUE THREAD

**Issue by SparkJiao** [HuangLK/llama-deepspeed#35]
Hi, 

I saw your code have used `PipeModelDataParallelTopology` API to specify the group size of pipeline parallelism and data parallel. However, I didn't see `DistribtuedSampler` is used for dataset shard. May I know if you have explored about this?

Thanks for your help very much!

Fangkai

**Comment by HuangLK** [comment]
The pipeline parallelism in DeepSpeed requires loading the same data in both the first and final stages. If `DistributedSampler` is used, it would disrupt the data consistency.

**Comment by SparkJiao** [comment]
Solved. Thanks for your sugestions!
