### ISSUE TITLE
训练时，loss =nan

### ISSUE THREAD

**Issue by zhangsanfeng86** [HuangLK/llama-deepspeed#8]
您好！ @HuangLK ，

在训练时，loss=nan，这个您遇到过吗？

**Comment by HuangLK** [comment]
`max_seq_len`设置多少？可能跟input过长有关

**Comment by zhangsanfeng86** [comment]
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/73547638/231796291-cf794701-e4c2-4609-a4d6-089943577155.png">

这是推理的结果，感觉没有自动停止生成，一直到了max lenth才停止

**Comment by HuangLK** [comment]
prompt长度超过max_seq_len时算cross_entropy会nan，因为没有有效的labels算loss。训练时过长数据的比例太高的，可能会频繁出现nan，此时建议加大max_seq_len或者过滤掉过长的数据，不然模型其实没有充分训练

**Comment by zhangsanfeng86** [comment]
谢谢
