### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by huiyangzhou** [HuangLK/llama-deepspeed#9]
deling_llama.py:134 in apply_rotary_pos_emb                                  │
│                                                                              │
│   131                                                                        │
│   132                                                                        │
│   133 def apply_rotary_pos_emb(q, k, cos, sin, position_ids):                │
│ ❱ 134 │   gather_indices = position_ids[:, None, :, None]  # [bs, 1, seq_len │
│   135 │   gather_indices = gather_indices.repeat(1, cos.shape[1], 1, cos.sha │
│   136 │   cos = torch.gather(cos.repeat(gather_indices.shape[0], 1, 1, 1), 2 │
│   137 │   sin = torch.gather(sin.repeat(gather_indices.shape[0], 1, 1, 1), 2 │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable
[2023-04-13 11:32:44,508] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 197
[2023-04-13 11:32:44,508] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 198
[2023-04-13 11:32:47,255] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 199
[2023-04-13 11:32:49,894] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 200
@HuangLK  do you know how this happend and how to solve it ?

**Comment by zhhao1** [comment]
> deling_llama.py:134 in apply_rotary_pos_emb │ │ │ │ 131 │ │ 132 │ │ 133 def apply_rotary_pos_emb(q, k, cos, sin, position_ids): │ │ ❱ 134 │ gather_indices = position_ids[:, None, :, None] # [bs, 1, seq_len │ │ 135 │ gather_indices = gather_indices.repeat(1, cos.shape[1], 1, cos.sha │ │ 136 │ cos = torch.gather(cos.repeat(gather_indices.shape[0], 1, 1, 1), 2 │ │ 137 │ sin = torch.gather(sin.repeat(gather_indices.shape[0], 1, 1, 1), 2 │ ╰──────────────────────────────────────────────────────────────────────────────╯ TypeError: 'NoneType' object is not subscriptable [2023-04-13 11:32:44,508] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 197 [2023-04-13 11:32:44,508] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 198 [2023-04-13 11:32:47,255] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 199 [2023-04-13 11:32:49,894] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 200 @HuangLK do you know how this happend and how to solve it ?

This may be a transformer version issue.

**Comment by HuangLK** [comment]
check out the latest commit :)

**Comment by huiyangzhou** [comment]
done
